# Generated by Django 4.2 on 2025-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_completed', models.DateField()),
                ('main_photo', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
